// ============================================================
// SADAQA STUDIO — global data
// All sample data lives here so screens stay focused on layout
// ============================================================

window.STUDIO_DATA = {
  // Picsum + grayscale gives consistent, muted-looking placeholders (Unsplash IDs are unreliable for content matching)
  photos: {
    well:        'https://picsum.photos/seed/sadaqa-well/1400/900?grayscale&blur=1',
    mosqueInt:   'https://picsum.photos/seed/sadaqa-mosqueint/1400/900?grayscale',
    mosqueExt:   'https://picsum.photos/seed/sadaqa-mosqueext/1400/900?grayscale',
    handsAid:    'https://picsum.photos/seed/sadaqa-aid/1400/900?grayscale',
    foodBox:     'https://picsum.photos/seed/sadaqa-iftar/1400/900?grayscale',
    community:   'https://picsum.photos/seed/sadaqa-community/1400/900?grayscale',
    snowy:       'https://picsum.photos/seed/sadaqa-winter/1400/900?grayscale',
    classroom:   'https://picsum.photos/seed/sadaqa-school/1400/900?grayscale',
    medicine:    'https://picsum.photos/seed/sadaqa-med/1400/900?grayscale',
    quranOpen:   'https://picsum.photos/seed/sadaqa-quran/1400/900?grayscale',
    handsOlder:  'https://picsum.photos/seed/sadaqa-elder/1400/900?grayscale',
    portrait1:   'https://picsum.photos/seed/sadaqa-p1/600/600?grayscale',
    portrait2:   'https://picsum.photos/seed/sadaqa-p2/600/600?grayscale',
    portrait3:   'https://picsum.photos/seed/sadaqa-p3/600/600?grayscale',
    portrait4:   'https://picsum.photos/seed/sadaqa-p4/600/600?grayscale',
    earthquake:  'https://picsum.photos/seed/sadaqa-quake/1400/900?grayscale',
    orphanage:   'https://picsum.photos/seed/sadaqa-orphan/1400/900?grayscale',
    qurban:      'https://picsum.photos/seed/sadaqa-qurban/1400/900?grayscale',
    cityNight:   'https://picsum.photos/seed/sadaqa-city/1400/900?grayscale'
  },

  user: {
    name: 'Yasmin Adan',
    initials: 'YA',
    role: 'admin',
    city: 'Stockholm',
    trustScore: 92,
    bankIdVerified: true,
  },

  categories: [
    { id: 'vatten',   name: 'Vatten',           count: 24, ico: 'droplet' },
    { id: 'mat',      name: 'Mat & Iftar',      count: 41, ico: 'gift' },
    { id: 'utbildning', name: 'Utbildning',     count: 18, ico: 'document' },
    { id: 'sjukvard', name: 'Sjukvård',         count: 12, ico: 'shield' },
    { id: 'akut',     name: 'Akut & katastrof', count:  9, ico: 'alert' },
    { id: 'zakat',    name: 'Zakat',            count: 33, ico: 'star' },
    { id: 'moske',    name: 'Moské & samfund',  count: 16, ico: 'building' },
    { id: 'foralder', name: 'Föräldralösa',     count:  8, ico: 'heart' },
  ],

  // Featured campaigns — used across discovery, marketing, profile
  campaigns: [
    {
      id: 'diabaly',
      slug: 'brunn-diabaly',
      title: 'En brunn för byn Diabaly — 280 personer får rent vatten',
      category: 'Vatten',
      location: 'Mali · Diabaly',
      photo: 'well',
      goal: 200000,
      raised: 148200,
      daysLeft: 12,
      donors: 287,
      org: 'Hjälpkraft Sverige',
      starter: 'Yasmin Adan',
      starterInit: 'YA',
      city: 'Stockholm',
      verified: true,
      zakat: true,
      tags: ['Granskad', 'Zakat-OK', 'Collab'],
      excerpt: 'Djupbrunn med handpump i centrala Mali. Räcker för 280 invånare och en grannby på sikt.'
    },
    {
      id: 'iftar-malmo',
      slug: 'iftar-malmo-2026',
      title: 'Iftar för 600 — Malmö moské, Ramadan 1447',
      category: 'Mat & Iftar',
      location: 'Sverige · Malmö',
      photo: 'foodBox',
      goal: 85000,
      raised: 71400,
      daysLeft: 6,
      donors: 412,
      org: 'Malmö islamiska center',
      starter: 'Omar Hassan',
      starterInit: 'OH',
      city: 'Malmö',
      verified: true,
      zakat: false,
      tags: ['Granskad', 'Lokalt'],
      excerpt: 'Tjugotvå kvällar med iftar för upp till 600 personer — familjer, studenter, ensamma äldre.'
    },
    {
      id: 'skola-gaza',
      slug: 'noddata-skola-gaza',
      title: 'Nödtält-skola i Rafah — 240 barn tillbaka till skolan',
      category: 'Utbildning',
      location: 'Gaza · Rafah',
      photo: 'classroom',
      goal: 320000,
      raised: 248900,
      daysLeft: 19,
      donors: 1041,
      org: 'Education for All',
      starter: 'Layla Mahmoud',
      starterInit: 'LM',
      city: 'Göteborg',
      verified: true,
      zakat: true,
      tags: ['Granskad', 'Zakat-OK', 'Akut'],
      excerpt: 'Tre tält-klassrum + lärarlöner i 6 månader, tillsammans med UNRWA-certifierade lärare.'
    },
    {
      id: 'syria-vinter',
      slug: 'vintertralna-syrien',
      title: 'Vinterpaket för 180 familjer i nordvästra Syrien',
      category: 'Akut & katastrof',
      location: 'Syrien · Idlib',
      photo: 'snowy',
      goal: 150000,
      raised: 91300,
      daysLeft: 4,
      donors: 524,
      org: 'Syriahjälpen',
      starter: 'Ahmad Khalil',
      starterInit: 'AK',
      city: 'Uppsala',
      verified: true,
      zakat: true,
      tags: ['Granskad', 'Akut', 'Slutspurt'],
      excerpt: 'Filtar, värmare, vinterkläder — sista veckan, det är iskallt nu.'
    },
    {
      id: 'qurban-2026',
      slug: 'qurban-somalia-2026',
      title: 'Qurban 2026 — 220 familjer i Somalia',
      category: 'Mat & Iftar',
      location: 'Somalia · Hargeisa',
      photo: 'qurban',
      goal: 240000,
      raised: 38400,
      daysLeft: 64,
      donors: 92,
      org: 'Hjälpkraft Sverige',
      starter: 'Yasmin Adan',
      starterInit: 'YA',
      city: 'Stockholm',
      verified: true,
      zakat: false,
      tags: ['Granskad', 'Qurban'],
      excerpt: 'Tidig planering inför Eid al-Adha. Får, getter, distribution direkt i Hargeisa-regionen.'
    },
    {
      id: 'aldreboende',
      slug: 'lakemedel-aldreboende-rinkeby',
      title: 'Läkemedelsstöd för äldre — Rinkeby & Tensta',
      category: 'Sjukvård',
      location: 'Sverige · Stockholm',
      photo: 'medicine',
      goal: 64000,
      raised: 22100,
      daysLeft: 22,
      donors: 78,
      org: 'Tensta islamiska center',
      starter: 'Fatima Begum',
      starterInit: 'FB',
      city: 'Stockholm',
      verified: true,
      zakat: true,
      tags: ['Granskad', 'Sverige', 'Zakat-OK'],
      excerpt: 'Receptkostnader och hjälpmedel för 24 äldre som inte täcks av frikort eller försäkring.'
    }
  ],

  // Cities for map view
  cities: [
    { name: 'Stockholm',  x: 64, y: 38, campaigns: 28, raised: '3,1 mkr' },
    { name: 'Göteborg',   x: 28, y: 50, campaigns: 19, raised: '1,8 mkr' },
    { name: 'Malmö',      x: 30, y: 86, campaigns: 16, raised: '1,4 mkr' },
    { name: 'Uppsala',    x: 62, y: 32, campaigns:  9, raised: '0,7 mkr' },
    { name: 'Västerås',   x: 52, y: 38, campaigns:  6, raised: '0,4 mkr' },
    { name: 'Örebro',     x: 44, y: 42, campaigns:  5, raised: '0,3 mkr' },
    { name: 'Linköping',  x: 50, y: 58, campaigns:  4, raised: '0,3 mkr' },
    { name: 'Umeå',       x: 64, y: 16, campaigns:  3, raised: '0,2 mkr' },
    { name: 'Norrköping', x: 52, y: 56, campaigns:  4, raised: '0,2 mkr' },
    { name: 'Helsingborg',x: 26, y: 80, campaigns:  3, raised: '0,2 mkr' }
  ],

  // Community threads
  threads: [
    { id: 't1', title: 'Hur räknar man zakat på sparpengar i ISK?', author: 'Ibrahim K.', city: 'Stockholm', replies: 14, dua: 32, hot: true, tag: 'Zakat' },
    { id: 't2', title: 'Bästa moskén för tarawih i Göteborg?',     author: 'Aisha R.',   city: 'Göteborg',  replies: 27, dua: 11, hot: false, tag: 'Ramadan' },
    { id: 't3', title: 'Erfarenheter — collab med en svensk hjälporganisation', author: 'Mahmood S.', city: 'Malmö', replies: 9, dua: 4, hot: false, tag: 'Insamlare' },
    { id: 't4', title: 'Sadaqa Jariya — projekt som lever vidare',  author: 'Nadia A.',   city: 'Uppsala',   replies: 41, dua: 88, hot: true, tag: 'Lärande' },
    { id: 't5', title: 'Resor till Mali — någon som har varit?',     author: 'Hassan O.',  city: 'Stockholm', replies: 6, dua: 2, hot: false, tag: 'Insamlare' },
  ],
  events: [
    { id: 'e1', date: '14 jun', title: 'Iftar-volontärer · Malmö moské', city: 'Malmö', going: 42, cap: 60, type: 'Volontär' },
    { id: 'e2', date: '21 jun', title: 'Föreningsmöte · Hjälpkraft',     city: 'Stockholm', going: 18, cap: 30, type: 'Förening' },
    { id: 'e3', date: '03 jul', title: 'Brunnsöverlämning live — Diabaly', city: 'Online', going: 124, cap: null, type: 'Stream' },
    { id: 'e4', date: '15 jul', title: 'Qurban-planering 2026',           city: 'Göteborg', going: 26, cap: 50, type: 'Förening' },
  ],

  // Audit findings — used by audit screen
  audit: [
    { surface: 'Marketing', sev: 'major', title: 'Hero stack känns för "kassaregister"-aktig',
      issue: 'Den nuvarande hero-kortstacken med produktbild över en mörk yta liknar ett SaaS-kassasystem — inte en insamlingsplattform. Risk att signalera fel kategori.',
      fix: 'Bytt mot ett enskilt, stort foto med en tunn kampanj-overlay. Inget kortspel. Hero-text till vänster, foto fullbredd till höger.' },
    { surface: 'Marketing', sev: 'minor', title: 'För många section-eyebrows ovanpå varandra',
      issue: 'Varje sektion har "STAR · LABEL"-eyebrow — repetitivt och stökigt.',
      fix: 'Bytt mot tunn numrerad rule (§ 01 — KATEGORIER) som tidskrifts-section break. Mindre dekor, mer struktur.' },
    { surface: 'Marketing', sev: 'minor', title: '"Powered by Corevo" i footern',
      issue: 'Plattformen är inte byggd på Corevo. Det är design-systemet vi lånar visuellt — inte tekniken.',
      fix: 'Tagit bort. Footern blev renare. Org.nr-raden återstår.' },
    { surface: 'Discovery', sev: 'major', title: 'Filtren ser ut men gör inget',
      issue: 'Kategori-pillarna, sorteringsmenyn, sökrutan — alla är dekorativa. Användaren förstår inte vad som händer när hen klickar.',
      fix: 'Riktig filtrering nu: klick på kategori filtrerar listan; sortering ändrar ordningen; sök filtrerar på titel. Allt på klient-state.' },
    { surface: 'Discovery', sev: 'minor', title: 'Listan saknar tom-state',
      issue: 'När inget matchar visas bara… inget.',
      fix: 'Tomt-läge med tydlig CTA: "Inget matchade — rensa filter eller starta en ny insamling".' },
    { surface: 'Fundraiser', sev: 'major', title: 'Donationskolumnen ankarär inte sticky',
      issue: 'På långa story-sidor förlorar man donationsknappen — måste scrolla upp. Konverteringsdödare.',
      fix: 'Höger kolumn är nu sticky med pris, progress och CTA. Stannar i blicken hela vägen.' },
    { surface: 'Fundraiser', sev: 'minor', title: 'Fem tabbar men man förstår inte ordningen',
      issue: '"Storyn → Mottagare → Bevis → Granskning → Dua" — varför just den ordningen? Bevis nämns 3:e men är ofta det viktigaste.',
      fix: 'Omflyttat: Storyn → Bevis → Mottagare → Granskning → Samtal. Bevis lyfts som det näst-första, eftersom det är det som skiljer Sadaqa från GoFundMe.' },
    { surface: 'Donate', sev: 'major', title: '"Belopp → Uppgifter → Bekräftelse" är tre steg som låter byråkratiskt',
      issue: 'Donator hatar former. Tre steg gör det värre.',
      fix: 'Plattat till ett steg: belopp + namn + Stripe i ett kort. BankID-snabbval för verifierade. "Som anonym" som tydlig knapp, inte gömd checkbox.' },
    { surface: 'Donate', sev: 'minor', title: 'Beloppsknapparna är hyperflexa men inkonsekventa',
      issue: '50/100/200/500/1000/Eget — fungerade okej, men "Eget" hoppar i sin egen rad.',
      fix: 'Sex jämna chips, "Eget" tar fokus och blir ett input-fält in-place när man klickar.' },
    { surface: 'Profile', sev: 'major', title: 'Trust-poäng 92/100 visas som ett bart tal — ingen vet vad det betyder',
      issue: '"92/100" utan kontext = misstanke. Är det bra? Hur räknas det?',
      fix: 'Hover/click ger förklaring: "BankID + 8 avslutade insamlingar + transparens-bevis i 7 av 8 = 92". Tydlig härkomst.' },
    { surface: 'Profile', sev: 'minor', title: 'Inget sätt att kontakta insamlaren',
      issue: 'Saknades helt. Vissa vill ställa en fråga innan de donerar.',
      fix: 'Tillagd: "Skicka fråga"-knapp. Öppnar en strukturerad form (inte fritt meddelande) — Q&A blir publikt på sidan om insamlaren svarar.' },
    { surface: 'Account', sev: 'major', title: 'Sidan känns inte som ett dashboard',
      issue: 'En lista med projektkort räcker inte. Insamlaren vill se: pengar in idag, donatörer denna vecka, beviskö, granskningsstatus.',
      fix: 'Omarbetat till dashboard-vy med KPI-rad högst upp, todo-kort, kö av väntande uppgifter, sen tabell över aktiva projekt.' },
    { surface: 'Account', sev: 'minor', title: 'Skapa-knappen är gömd',
      issue: 'En primary CTA "Starta ny insamling" satt i högerhörnet, lätt att missa.',
      fix: 'Promint plats i KPI-raden + en "+ Ny insamling"-knapp i admin-sidebar.' },
    { surface: 'Map', sev: 'major', title: 'Kartan är en SVG-platshållare — sägs vara "karta" men är en form',
      issue: 'Användaren förväntar sig en interaktiv karta — vi ger en silhuett.',
      fix: 'Sverige-silhuett med klickbara stad-prickar; click ger sidopanel med stadens insamlingar. Inte Mapbox, men känns levande.' },
    { surface: 'Community', sev: 'minor', title: 'Threads och events blandas',
      issue: 'En "Community"-sida som visar både samtal och events skapar förvirring.',
      fix: 'Tabb-delning: "Samtal" och "Händelser" på samma sida, default på samtal. Dua-knappen behållen — det är det som skiljer denna från Facebook.' },
    { surface: 'Globalt', sev: 'major', title: 'Topbar är samma överallt oavsett roll',
      issue: 'Insamlare och admin ser samma navigering som besökare — orienteringen försvinner.',
      fix: 'Tre chrome-lägen: Publik (logo + main nav + hamburgare + login), Insamlare (samma + "Mina sidor"-genväg), Admin (dashboard-sidebar + minimal topbar med breadcrumbs och systemstatus).' },
    { surface: 'Globalt', sev: 'minor', title: 'Hamburgare saknas',
      issue: 'På mindre skärmar och i mobil-läge — ingen menyfallback.',
      fix: 'Hamburgare nu på alla publika ytor (höger sida av topbar). Öppnar en mörk drawer med alla destinationer i serif.' },
  ],
};
